sudo:       required
language:   generic
services:   docker

# Docs of the options: https://github.com/Strauman/travis-latexbuild/tree/master#configuration-options
tex-config:
- tex-scheme=full
- push-type=none
- build-pattern=AMGEO_WiSe2018/AMGEO.tex,ANGA_WiSe2018/ANGA.tex,FEM_WiSe2018/FEM.tex,MFANA_WiSe2018/MFANA.tex,MSTAT_WiSe2018/MSTAT.tex,ORDSTR_WiSe2018/ORDSTR.tex,PDEANA_WiSe2018/PDEANA.tex,PDENM_WiSe2018/PDENM.tex,WTHM_WiSe2018/WTHM.tex,nebenfaecher/FormaleSysteme_WiSe2018/FORM.tex,NLANA_SoSe2019/NLANA.tex,STOCHP_SoSe2019/STOCHP.tex,SCPROG_SoSe2019/SCPROG.tex,MMAM_LM_SoSe2019/MMAM_LM.tex,MMAM_ST_SoSe2019/MMAM_ST.tex,KONGEO_SoSe2019/KONGEO.tex,DISMAT_SoSe2019/DISMAT.tex,ALGTOP_SoSe2019/ALGTOP.tex,Kategorientheorie_SoSe2019/KAT.tex,SCCOMP_SoSe2019/SCCOMP.tex,PDENMW_SoSe2019/PDENMW.tex,DISOPT_SoSe2019/DISOPT.tex,STOCAL_SoSe2019/STOCAL.tex,ALLALG_SoSe2019/ALLALG.tex
- latexmk-flags=-halt-on-error
# Check at https://www.ctan.org/pkg/package-name in which TeX Live package a LaTeX package is contained.

# We will use the docker image from https://hub.docker.com/r/strauman/travis-latexbuild/
script:
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind strauman/travis-latexbuild:full

deploy:
  provider: releases
  api_key:
    secure: bVfTJ7eG9SUKWZkgAzIPsE4Gcwe+UvOK0u6QR3ig61dUdqvxmbDuxjRgZWjTHe4YyofnKY3CfCIImCP+t5/JbNdqghEevDxif9j/YFdycPkDjTk8yvQ4OSZc//3/zShjpLx6gAS5dsiRxK6E0bQuEfkPay6/8eIe7DXLaRdg1SVipBlNLgT8sDH5TrdjTUDZ8nsNK+DGrUuxYEidByyzW7VmpgKa3WIOeQVsC2tJISWV+mvC07P4Ip9otCAz7i2s+ed+Q4YlZ0XpZYK0qaqGxuPmZv62oheqxY0peq20iUB5xGp9i4lCjVpnDoD1rQjgzXcVgymYs7iueROuWnrq1iRWTXkKsHmb/kpwUAA2e+pIvDHa3U2jKsRO70+sshsd64lyyKSHkL57Hc4SrKJy167+h5ZKMXnUL55lCJ0Nr8EZ9ChK8I/sI5YvSlNNqgi4nbd0k9waKsHrH8tPecsM8x4pXcfC/nnwzNnhGmLBg9QfH3qc5ieLlT4MUOY+qOzNFj/lsPWHOuJFO/QX8z0g1Scc/rTjc9f04KmbzmDceRrUDODWlwU6hpuwsVDJOBZ7UyeqFK7KHKQlp9hF3RMYThwbiX/3Vmlly8KQHWI0YqdCtPx7PG+wq61LIPeVdMLId4TczDA4tplnU9KH6sFY4U3t1RCe9s/XlskxinCtn6M=
  file:
  - ./bin/AMGEO.pdf
  - ./bin/ANGA.pdf
  - ./bin/FEM.pdf
  - ./bin/MFANA.pdf
  - ./bin/MSTAT.pdf
  - ./bin/ORDSTR.pdf
  - ./bin/PDEANA.pdf
  - ./bin/PDENM.pdf
  - ./bin/WTHM.pdf
  - ./bin/FORM.pdf
  - ./bin/ALGTOP.pdf
  - ./bin/DISMAT.pdf
  - ./bin/DISOPT.pdf
  - ./bin/KAT.pdf
  - ./bin/KONGEO.pdf
  - ./bin/MMAM_LM.pdf
  - ./bin/MMAM_ST.pdf
  - ./bin/NLANA.pdf
  - ./bin/PDENMW.pdf
  - ./bin/SCCOMP.pdf
  - ./bin/SCPROG.pdf
  - ./bin/STOCAL.pdf
  - ./bin/STOCHP.pdf
  name: >-
      Mitschriften zum Ende der
      $(python3 -c 'from datetime import date as d; import math; print(math.ceil((d.today() - d(2018, 10, 7)).days / 7))').
      Woche des WS 2018
  skip_cleanup: true
  on:
    tags: true
    repo: LostInDarkMath/MatheMaster
